### ISSUE TITLE
No matching node for: snowplow_web_cmp_stats

### ISSUE THREAD

**Issue by petersentaylor** [snowplow/dbt-snowplow-web#142]
## Describe the bug
The `consent.yml` file references `snowplow_web_cmp_stats` which has been renamed to `snowplow_web_consent_cmp_stats`. This causes a few warnings when compiling dbt.

## Steps to reproduce

`dbt compile`
## Expected results
No Warnings

## Actual results
`[WARNING]: Did not find matching node for patch with name 'snowplow_web_cmp_stats' in the 'models' section of file 'models/optional_modules/consent/consent.yml'`
`[WARNING]: Test 'test.snowplow_web.unique_snowplow_web_cmp_stats_event_id.ea39766dc6' (models/optional_modules/consent/consent.yml) depends on a node named 'snowplow_web_cmp_stats' which was not found`
`[WARNING]: Test 'test.snowplow_web.not_null_snowplow_web_cmp_stats_event_id.641558e3db' (models/optional_modules/consent/consent.yml) depends on a node named 'snowplow_web_cmp_stats' which was not found`

## System information
**The contents of your `packages.yml` file:**
```yml
# contents goes here
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0

  - package: dbt-labs/snowplow
    version: 0.15.0

  - package: snowplow/snowplow_web
    version: 0.12.2
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.3.0
```

**The operating system you're using:**
macOS 13.0.1

**The output of `python --version`:**
Python 3.10.6

## Are you interested in contributing towards the fix?
Yes!
