### ISSUE TITLE
snowplow_web_sessions table is not correctly handling different app_id

### ISSUE THREAD

**Issue by dkbrkjni** [snowplow/dbt-snowplow-web#230]
## Describe the bug
Events with same `domain_sessionid` but different `app_id` is not correctly represented in the `snowplow_web_sessions` table.

## Steps to reproduce
1. Set up two trackers with different `app_id` on the same website.
2. Browser the website and check that the `domain_sessionid` is identical for events tracked with both trackers.
3. Once the dbt models has run on the data tracked in previous step, look for the events in `snowplow_web_base_sessions_this_run` and verify the table contains events with an identical `domain_sessionid` but different `app_id`.
4. Now look in the `snowplow_web_sessions` table.  There is only one row with the `domain_session_id` tracked in step 2.  The row has an `app_id` with one of the app_id's. 

## Expected results
The `snowplow_web_sessions` table to contains two rows. One per each `app_id` , both rows with identical `domain_sessionid`.

## Actual results
The `snowplow_web_sessions` table to contains one rows, with one of the `app_id`.

## System information
**The contents of your `packages.yml` file:**
```yml
# add dependencies. these will get pulled during the `dbt deps` process.
---
packages:
  # https://hub.getdbt.com/dbt-labs/dbt_utils/latest/
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]

  - package: snowplow/snowplow_web
    version: 0.14.0

  - package: snowplow/snowplow_mobile
    version: 0.7.0

  - package: snowplow/snowplow_media_player
    version: 0.5.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.4.8
```

**The operating system you're using:**

**The output of `python --version`:**
