### ISSUE TITLE
package.yml has constraint [">=0.15.0", "<0.16.0"] on snowplow_utils while latest is 0.17.2

### ISSUE THREAD

**Issue by jsvisser82** [snowplow/dbt-snowplow-web#243]
## Describe the bug
The package.yml in v1.0.1 has a constraint on versions [">=0.15.0", "<0.16.0"] for the snowplow_utils, while the latter has 0.17.2 as latest release. The new [snowplow_utils](https://github.com/snowplow/dbt-snowplow-utils/releases/tag/0.17.2) version is necessary to fix a bug introduced in dbt where they alias delete+insert statements which breaks syntax on postgres.

## Steps to reproduce
n/a

## Expected results
dbt deps installs snowplow_utils v0.17.2

## Actual results
dbt deps fails

## Screenshots and log output
08:42:58 Encountered an error:
Version error for package snowplow/snowplow_utils: Could not find a satisfactory version from options: ['=0.17.2', '>=0.15.0', '<0.16.0']

## System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: snowplow/snowplow_web
    version: [">=1.0.0", "<2.0.0"]
  - package: metaplane/dbt_expectations
    version: 0.10.8
  - package: snowplow/snowplow_utils
    version: 0.17.2
```

**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Latest
```

**The operating system you're using:**
n/a

**The output of `python --version`:**
n/a
