### ISSUE TITLE
Bump snowplow_utils version

### ISSUE THREAD

**Issue by bill-warner** [snowplow/dbt-snowplow-web#55]
### Issue

Currently the web and mobile package import different versions of the utils package.

This results in an error when trying to install both the web and mobile package:

```yml
#packages.yml
packages:
  - package: snowplow/snowplow_web
    version: [">=0.5.0", "<0.6.0"]
  - package: snowplow/snowplow_mobile
    version: [">=0.1.0", "<0.2.0"]
```

![image](https://user-images.githubusercontent.com/71764352/152499699-d099fdb0-2c00-48ff-8660-dfa88b813b90.png)

### Solution

Bump the utils import in the web package to align with that of the mobile package. This change should be made as a patch release.
